version: '3.3'
services:
  neo4j:
    image: 'neo4j:latest'
    container_name: neo4j-db
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - '$HOME/neo4j/data:/data'
      - '$HOME/neo4j/logs:/logs'
      - '$HOME/neo4j/import:/var/lib/neo4j/import'
      - '$HOME/neo4j/plugins:/plugins'
    environment:
      - NEO4J_AUTH=neo4j/secret
